// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using boutique_zyx_api;

#nullable disable

namespace boutique_zyx_api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("boutique_zyx_api.Entidades.Pedido", b =>
                {
                    b.Property<int>("NumeroPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("NumeroPedido"));

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaDespacho")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaEntrega")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaPedido")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaRecepcion")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("Repartidor")
                        .HasColumnType("int");

                    b.Property<int>("Vendedor")
                        .HasColumnType("int");

                    b.HasKey("NumeroPedido");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("boutique_zyx_api.Entidades.Producto", b =>
                {
                    b.Property<string>("SKU")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Etiquetas")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Tipo")
                        .HasColumnType("longtext");

                    b.Property<string>("UnidadMedida")
                        .HasColumnType("longtext");

                    b.HasKey("SKU");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("boutique_zyx_api.Entidades.ProductoPedido", b =>
                {
                    b.Property<int>("NumeroPedido")
                        .HasColumnType("int");

                    b.Property<string>("SKU")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int?>("PedidoNumeroPedido")
                        .HasColumnType("int");

                    b.Property<string>("ProductoSKU")
                        .HasColumnType("varchar(255)");

                    b.HasKey("NumeroPedido", "SKU");

                    b.HasIndex("PedidoNumeroPedido");

                    b.HasIndex("ProductoSKU");

                    b.ToTable("ProductoPedidos");
                });

            modelBuilder.Entity("boutique_zyx_api.Entidades.Usuario", b =>
                {
                    b.Property<int>("CodigoTrabajador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CodigoTrabajador"));

                    b.Property<string>("CorreoElectronico")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("Puesto")
                        .HasColumnType("longtext");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .HasColumnType("longtext");

                    b.Property<string>("User")
                        .HasColumnType("longtext");

                    b.HasKey("CodigoTrabajador");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("boutique_zyx_api.Entidades.ProductoPedido", b =>
                {
                    b.HasOne("boutique_zyx_api.Entidades.Pedido", "Pedido")
                        .WithMany("ProductoPedidos")
                        .HasForeignKey("PedidoNumeroPedido");

                    b.HasOne("boutique_zyx_api.Entidades.Producto", "Producto")
                        .WithMany("ProductoPedidos")
                        .HasForeignKey("ProductoSKU");

                    b.Navigation("Pedido");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("boutique_zyx_api.Entidades.Pedido", b =>
                {
                    b.Navigation("ProductoPedidos");
                });

            modelBuilder.Entity("boutique_zyx_api.Entidades.Producto", b =>
                {
                    b.Navigation("ProductoPedidos");
                });
#pragma warning restore 612, 618
        }
    }
}
